#%RAML 1.0 NamedExample

AccountsExampleGET:
-
  id: 1 
  firstName: Aly
  lastName: Lazaro
  address:
    postal: "419684"
    country: SG
  miles: 1000
  creationDate: 2016-02-28T16:41:41.090Z 
  type: member
-
  id: 2
  firstName: Maria
  lastName: Alyanna
  address:
    postal: "1420"
    country: PH
  miles: 2000
  creationDate: 2016-03-28T16:41:41.090Z 
  type: vip