#%RAML 1.0 NamedExample

AccountsExamplePOST:
-
  firstName: Aly
  lastName: Lazaro
  address:
    postal: "419684"
    country: SG
  miles: 1000
  type: member
-
  firstName: Maria
  lastName: Alyanna
  address:
    postal: "1420"
    country: PH
  miles: 2000
  type: vip